### ISSUE TITLE
Private package source doesn't work.

### ISSUE THREAD

**Issue by jeffhli** [adrian-pavel/visual-nuget#17]
I have set the config like this: 
![image](https://user-images.githubusercontent.com/60603443/174334374-c71b1c57-af6d-4296-9835-3aeacbe60c11.png)
But it doesn't work due to the request without the authorization header.
![image](https://user-images.githubusercontent.com/60603443/174334490-250e3e8c-b529-4738-b42e-06752c31d6b4.png)

**Comment by adrian-pavel** [comment]
Hello. I haven't tested Artifactory but the way you've set the token seems to be OK according to their docs. Can you maybe try and open the developer tools in VS code and see all the requests happening? Also maybe try Basic authentication instead of Bearer? Like the docs say about Azure DevOps.
One issue could be if the behavior of the Artifactory API is similar to GitHub Packages, in that it does not provide the proper origin headers. I've created a [stackoverflow post here](https://stackoverflow.com/questions/71307210/github-nuget-api-request-blocked-by-cors-because-of-authorization-header) bout it but unfortunately got no responses. If anyone reading this has any idea how to fix this, please let me know.

**Comment by jeffhli** [comment]
@adrian-pavel I have used the basic authentication to try connect, but still get an error.
![image](https://user-images.githubusercontent.com/60603443/174513319-52ba5623-a2be-488a-9c11-7bad22f04f8a.png)

**Comment by mbastiani** [comment]
Hello. I managed to make it work using the tip from this link:
https://github.com/VSCodium/vscodium/issues/746#issuecomment-891312271

1) Run VSCode with --disable-web-security
2) Edit ~/.vscode-oss/argv.json ​and add the line "enable-browser-code-loading": false
