### ISSUE TITLE
overwrute default nuget.org

### ISSUE THREAD

**Issue by yedajiang44** [adrian-pavel/visual-nuget#9]
Due to network peculiarities, I had to replace the default source with a `CDN`, but when I added a `CDN` named `nuget.org`, the list showed two `nuget.org`

can add regional language support(unimportance)

**Comment by adrian-pavel** [comment]
Hello. I could add the option to disable the default nuget.org source but not sure when I will get to it. The next priority for me would be to add unit and integration tests to make future development and changes easier and more stable.
In the mean time, you could add your custom nuget.org with a different name to be able to know which one is which. The name is only for display purposes and can be anything.
I know that this is less than ideal since the default one will still be first in the list and selected when you open.
I will leave the issue open and update it once I fix it.

**Comment by yedajiang44** [comment]
Ideally, the default `nuget.org` can be edited. Will the next version support multi-project operations?like `NuGet Gallery`，but it doesn't update

**Comment by adrian-pavel** [comment]
Yes, that's a good idea, I can add the default to the settings.
The plan for the future is to replicate as much functionality from the Visual Studio Nuget Package Manager as possible. Including multiple projects at a time and sln files etc.

**Comment by yedajiang44** [comment]
Looking forward to the new version, I will close this iss first

**Comment by adrian-pavel** [comment]
Added this functionality in version 0.2.0.

**Comment by yedajiang44** [comment]
> Added this functionality in version 0.2.0. @[yedajiang44](https://github.com/yedajiang44) Please consider reviewing the extension on the marketplace if you haven't already so that more people can find it.

wow! nice~thank you for your work~~~~
